# Setup cluster 
- hosts: kubemaster
  remote_user: ubuntu
  become: yes
  environment: 
    HOME: /home/ubuntu/
  tasks:
   # Initialize Cluster. The log is also used to prevent an second initialization
   - name: Initialize Cluster
     shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_init.log
     args:
       chdir: $HOME
       creates: cluster_init.log

   # Create the configuration / configuration directory
   - name: Create .kube directory
     file:
       path: $HOME/.kube
       state: directory
       mode: 0755
       recurse: yes

   - name: Copy admin.conf to the user's kube directory
     copy:
       src: /etc/kubernetes/admin.conf
       dest: $HOME/.kube/config
       remote_src: yes
       owner: ubuntu
   # Setup Flannel network 

   - name: Setup Flannel. Use log to prevent second installation
     shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> flannel_setup.log
     args:
       chdir: $HOME
       creates: flannel_setup.log

   - name: Create token to join cluster
     shell: kubeadm token create --print-join-command
     register: join_command

   - name: Set join command as fact
     set_fact:
       join_command: "{{ join_command.stdout_lines[0] }}"

# Join Cluster with each kube-node
- hosts: kubeworkers
  become: yes
  tasks:

    - name: Wait for master's port 6443
      wait_for: "host={{ hostvars['master']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"
    - name: Joining to the cluster
      become: yes
      shell: "{{ hostvars['master']['join_command'] }} >> node_join.log" 
      args:
        chdir: $HOME
        creates: node

# tasks to install-helm on master node
- hosts: kubemaster
  become: yes
  tasks:
  - name: Getting helm install script...
    shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    args:
      chdir: /home/ubuntu/
  - name: Installing helm... (1)
    become: yes
    shell: chmod 700 get_helm.sh
    args:
      chdir: /home/ubuntu/
  - name: Installing helm... (2)
    become: yes
    shell: /home/ubuntu/get_helm.sh